### ISSUE TITLE
Need help to use this library in Swift project

### ISSUE THREAD

**Issue by boomi1990** [nverinaud/NVSlideMenuController#34]
Hi,

I have already used NVSlideMenuController in Objective C project. That is working fine. Now I am working in Swift project.

Please tell me how to use this NVSlideMenuController in Swift project.

Thanks,
Boominadha Prakash M

**Comment by nverinaud** [comment]
Hi,

This stackoverflow answer may help you : http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

Please reopen this issue if you encounter a problem using NVSlideMenuController in Swift.

Nicolas
