### ISSUE TITLE
UITableViewCell swipe gesture is conflicting with Slide Menu gesture

### ISSUE THREAD

**Issue by boomi1990** [nverinaud/NVSlideMenuController#35]
Hi,

I am facing problem because of the SlideMenu Controller Pan Gesture conflicts with UITableViewCell Swipe Gesture.

CommitEditingStyle TableView function is not working. Please tell me the solution to fix this problem.

**Comment by nverinaud** [comment]
Hi @boomi1990,

I suggest you to disable the slide menu controller pan gesture when using an editable table view.

Please feel free to reopen this issue if this does not solve your problem :-)
